name: Update Checker
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check if file exists
        run: |
          if [[ ! -f apks/latest-parsed-version.md ]]; then
            echo "The file apks/latest-parsed-version.md was not found. Creating it."
            mkdir -p apks
            touch apks/latest-parsed-version.md
          fi
      # - name: Get latest release from ReVanced/revanced-patches
      - name: Get latest release from MorpheApp/morphe-patches
        id: latest-release
        run: |
          # LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/ReVanced/revanced-patches/releases/latest | jq -r '.tag_name')
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/MorpheApp/morphe-patches/releases/latest | jq -r '.tag_name')
          if [ "$LATEST_RELEASE" == "null" ] || [ -z "$LATEST_RELEASE" ]; then
            echo "Couldn't fetch latest release. Workflow halted!"
            echo "skip_update=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "tag_name=$LATEST_RELEASE" >> $GITHUB_OUTPUT
      - name: Compare with local version
        id: compare-version
        if: steps.latest-release.outputs.skip_update != 'true'
        run: |
          LOCAL_VERSION=$(cat apks/latest-parsed-version.md)
          if [ "$LOCAL_VERSION" == "${{ steps.latest-release.outputs.tag_name }}" ]; then
            echo "Already up-to-date!"
          else
            echo "Local reported version doesn't match fetched version, updating local version."
            echo "${{ steps.latest-release.outputs.tag_name }}" > apks/latest-parsed-version.md
            git add apks/latest-parsed-version.md
            git commit -m "Update latest-parsed-version.md"
            git push
            echo "trigger_build=true" >> $GITHUB_OUTPUT
          fi
      - name: Verify local version update
        if: ${{ steps.compare-version.outputs.trigger_build == 'true' }}
        run: |
          UPDATED_VERSION=$(cat apks/latest-parsed-version.md)
          if [ "$UPDATED_VERSION" == "${{ steps.latest-release.outputs.tag_name }}" ]; then
            echo "Local version updated successfully!"
          else
            echo "Error updating local version control file, halting workflow!"
            exit 1
          fi
      - name: Trigger build workflow
        if: ${{ steps.compare-version.outputs.trigger_build == 'true' }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: "Build & Release" # build-apk.yml
          token: ${{ secrets.GITHUB_TOKEN }}